### ISSUE TITLE
Need instruction on running the project

### ISSUE THREAD

**Issue by rampanda7** [OpenMatch/TASTE#1]
Hi,

Please give instruction on how to run the file,  For someone getting started with OpenMatch it is not that easy to understand how to run the file.  Went through the read me file, Could find anything regarding running the file.

**Comment by mssssss123** [comment]
Hello,
All script files for running this project are provided in the reproduce folder. Just follow the readme steps of reproduce to run: call the data processing script, training script, evaluation script and test script. At the same time, all data set files, checkpoints, running logs, and tensorboard have been provided for reference.

I will update this project by writing a more simple and easy-to-understand guide as soon as possible.

Regarding the openmatch you mentioned, please tell me further what is unclear and we will improve it as soon as possible.

If you have any questions, please feel free to contact me. My email address is also provided on the project homepage.

**Comment by Zhipeng-Xu** [comment]
We have simplified the reproduction step and you can find it in the README.

If you are interested in OpenMatch, you are also welcome to learn how to use it.
A tutorial on how to use the OpenMatch toolkit can be found at the following link.
https://openmatch.readthedocs.io

**Comment by Zhipeng-Xu** [comment]
> Hi,
> 
> Please give instruction on how to run the file, For someone getting started with OpenMatch it is not that easy to understand how to run the file. Went through the read me file, Could find anything regarding running the file.



> Hi,
> 
> Please give instruction on how to run the file, For someone getting started with OpenMatch it is not that easy to understand how to run the file. Went through the read me file, Could find anything regarding running the file.

We have simplified the reproduction step and you can find it in the README.

If you are interested in OpenMatch, you are also welcome to learn how to use it.
A tutorial on how to use the OpenMatch toolkit can be found at the following link.
https://openmatch.readthedocs.io/

**Comment by Pab1x** [comment]
We have simplified the reproduction step and you can find it in the README.

If you are interested in OpenMatch, you are also welcome to learn how to use it.
A tutorial on how to use the OpenMatch toolkit can be found at the following link.
https://openmatch.readthedocs.io/

**Comment by Zhipeng-Xu** [comment]
closed
