### ISSUE TITLE
LoRA with OpenDelta

### ISSUE THREAD

**Issue by eric1anderson** [OpenMatch/TASTE#11]
Hi,

I am interested in applying LoRA to this model architecture. I see OpenDelta mentioned in the code and I am able to define a parameter efficient method as an argument in the train.sh scripts. Though OpenDelta  appears to be having trouble adding LoRA to custom TASTEModel class. Have you explored adding LoRA to TASTE with any success?

Thank you!

**Comment by mssssss123** [comment]
Hi, this code does not use OpenDelta, so I have not tried it.

**Comment by eric1anderson** [comment]
Okay, thank you!
