### ISSUE TITLE
One bug I meet when I reproduce your work

### ISSUE THREAD

**Issue by onetance** [OpenMatch/TASTE#13]
Hi！what a wonderful work！
One bug I meet when I reproduce your work

![image](https://github.com/user-attachments/assets/90e96864-ee14-4d2e-acf4-e2e37b42eae1)
I've kept all my libraries the same as yours
![image](https://github.com/user-attachments/assets/64672eee-4ae7-47cd-bdb2-d71db576fc69)
can you  help me

**Comment by onetance** [comment]
I updated datasets and solved it successfully！Thank you

**Comment by mssssss123** [comment]
Hello! I’m glad your issue has been resolved.🎉

 If you have any further questions during the reproduction process, please feel free to reach out.
