### ISSUE TITLE
Error when running model on beauty dataset

### ISSUE THREAD

**Issue by ananv21** [OpenMatch/TASTE#4]
Hello,

I'm trying to run the model on the beauty dataset (using the configurations given in train_beauty.sh in the reproduce folder) but I seem to be getting the following error:

**Traceback (most recent call last):

  File "C:\Users\anvasudev\Desktop\service contracts\OpenMatch\OpenMatch\src\TASTE\train.py", line 129, in <module>

    main()

  File "C:\Users\anvasudev\Desktop\service contracts\OpenMatch\OpenMatch\src\TASTE\train.py", line 121, in main

    trainer.train()

  File "C:\Users\anvasudev\Anaconda3\lib\site-packages\transformers\trainer.py", line 1521, in train

    return inner_training_loop(

  File "C:\Users\anvasudev\Anaconda3\lib\site-packages\transformers\trainer.py", line 1837, in _inner_training_loop

    self.state.epoch = epoch + (step + 1) / steps_in_epoch

ZeroDivisionError: division by zero**

According to this training message I think this is because the number of training examples is 0 but I'm not sure why since the data seems to be getting loaded in and parsed appropriately: 

******* Running training *****
  Num examples = 0

  Num Epochs = 30

  Instantaneous batch size per device = 8

  Total train batch size (w. parallel, distributed & accumulation) = 8

  Gradient Accumulation steps = 1

  Total optimization steps = 30**

Do you know why this might be happening?

**Comment by mssssss123** [comment]
Hi, I noticed that your Num examples = 0, which means your data is not being loaded. In fact I have not encountered this problem, I think it may be a data file path problem

Correct running results:
***** Running training *****
  Num examples = 131413
  Num Epochs = 30
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 492810


Please make sure there is no problem with these two commands
--train_path ../TASTE/data/beauty/train_name.jsonl \
--eval_path ../TASTE/data/beauty/valid_name.jsonl \

**Comment by Zhipeng-Xu** [comment]
Hi.
This looks like a data loading issue, please check if the dataset is placed wisely. We have detailed data processing steps in the README.

**Comment by eureka336** [comment]
This error may occur when running openmatch in the windows environment. You can try linux.

**Comment by mssssss123** [comment]
Replace trainer.py:152-157 lines, which may solve your problem.  I haven't tried this modification yet. If this method still doesn't work, or if you have other questions, please contact me.

class SStreamTrainDatasetMixin(StreamTrainDatasetMixin):
    def __iter__(self):
        if not self.is_eval:
            epoch = int(self.trainer.state.epoch)
            _hashed_seed = hash(self.trainer.args.seed)
            self.dataset.set_epoch(epoch)
            return iter(self.dataset.map(self.get_process_fn(epoch, _hashed_seed), remove_columns=["positives", "negatives"]))
        return iter(self.dataset.map(self.get_process_fn(0, None), remove_columns=self.all_columns))

class StreamDRTrainDataset(StreamTrainDatasetMixin, TasteTrainDataset):
    pass


class MappingDRTrainDataset(SStreamTrainDatasetMixin, TasteTrainDataset):
    pass

**Comment by ananv21** [comment]
Hello, 
I tried using this approach (I also checked my training path and it seems to be fine) but I'm still facing the same error and the number of examples is showing as 0. Is there anything else you could recommend to fix this?

Thanks!

**Comment by mssssss123** [comment]
Hello, I tried several situations and couldn't reproduce this bug, so I'm not sure what caused your data to show 0.

I have the following guesses, you can try them:

1. Please make sure the data file itself is correct, we provide steps to build the data. Or you can directly download the data I provided.
2. I guess it is an environment problem, especially the transformer version. You can try to use versions below 4.24.0.
3. If none of the above steps can solve the problem, please manually debug it to better determine where the data starts to be 0.

I hope to solve this problem for you as soon as possible. Please provide me with more information to locate this problem. Please feel free to contact me.
