### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by ananv21** [OpenMatch/TASTE#5]
Hello, 

I want to run the model on one of my own datasets, what code could I use to preprocess it into the appropriate format? I tried referring to gen_dataset_example.py but I'm not sure what I should be setting the arguments as for the run_recbole function.

Any help would be appreciated!

**Comment by mssssss123** [comment]
Hello，
Could you show me some details about your own dataset?
I'm not sure whether you need to use RecBole for data processing, because it's the same if you process it yourself. I just want to make a direct comparison with the baseline model DIF-SR.
It seems to me that you can add code to load your dataset and modify load_data and load_item_data in dataloader.py, as long as it converts user sequence and items into text format.

**Comment by mssssss123** [comment]
Add,
build_train.py and gen_all_items.py also need to be modified. You can give me some examples and I will help you complete this part of the expansion.
In addition, if you want to use Recbole to process data, I think you can refer to: <https://github.com/RUCAIBox/RecSysDatasets>

**Comment by ananv21** [comment]
Hello, 
Right now my data is a csv file formatted in tabular format like this:

User    |     Item        |      Item Description     |   Date
  1        |         "a"          |          "xyz"                       |    2/9/23

Is there any code in this repo or that you know of elsewhere that I could use to convert my data into the same format as the sample data?

**Comment by mssssss123** [comment]
Sorry our code itself does not take into account extensions to other datasets. But I think your data can be easily extended into our code. Our code only needs to be able to provide input in the form of text.

If you want to use ready-made code, it is recommended to use the Recbole data set conversion tool <https://github.com/RUCAIBox/RecSysDatasets/tree/master>, and then write a yaml file like<https://github.com/AIM-SE/DIF-SR/blob/main/configs/Amazon_Beauty.yaml> to call Recbole to process the data <https://github.com/RUCAIBox/RecBole>. How to obtain the data processed by Recbole, you can refer to the code example I provided.
