### ISSUE TITLE
One bug I meet when I reproduce your work

### ISSUE THREAD

**Issue by virtual-world-oss** [OpenMatch/TASTE#9]
When I reproduce your work, I meet the bug in transformers.trainer.py.
The bug is 
![image](https://github.com/OpenMatch/TASTE/assets/72393352/27e64f91-195b-48f4-9c21-5d8f4892bcfd)
The bug means 'inputs' should be a dict, but it is a list at runtime.
I check the source of the inputs and discover that it comes from eval_dataloader.
I have no idea what cause the bug. Maybe transformers version?
Can you provide some ideas to solve this bug?
Thank you very much.

**Comment by mssssss123** [comment]
Hi,
I think you have the same problem as them #3 #8 . This is a problem caused by the Transformer version being high. Using versions below 4.24.0 should not have this problem.
Hope this helps you solve this problem.

**Comment by virtual-world-oss** [comment]
Thank you for your reply.  I will try a lower version.
